spring:
  datasource:
    url: jdbc:mysql://localhost:3306/colorgame
    username: ${JDBC_USER}
    password: ${JDBC_PASS}
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

schedule-time: 60000

jwt:
  secret: ${JWT_SECRET}